1. What is a trivially solvable problem ?

A combination where GCD is always predictable.

2. What is a corresponding solution ?

Solution is 0, since 0 can be divided evenly by every number.
Hence the GCD of 0 and n will always be n.

3. How do we generate new problems that are more
easily solvable than the original problem? Is there one
new problem that we generate or are there several?

The new problem is generated by finding the remainder of
smaller number into larger number. There is one new problem here.

4. Is the solution of the given problem the same as the
solution of (one of) the new problems? Or, do we need to
combine the solutions to create a solution for the original
problem? And, if so, do we need anything from the original
problem data?

Yes the solution to the new problem is same as the original.
